#!/bin/bash
# description: Script to easily start, stop or restart TWCManager, or check the status.
# last update: Feb 2, 2020 by laur3ns

start() {
   echo "Starting TWCManager..."
   screen -dm -S twc -L -Logfile ~/scripts/twc/TWCManager.log ~/scripts/twc/TWCManager.py
}

stop() {
   echo "Stopping TWCManager..."
    killall TWCManager.py
}

status() {
   # ps auxww | fgrep TWCManager | fgrep -v grep
   echo -n "TWC Manager is "
   screen -ls twc -q || echo "NOT RUNNING" && echo "RUNNING, to connect run 'screen -r twc' and exit with Ctrl-A, Ctrl-D"
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       status
       ;;
    status)
       status
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
