#!/bin/bash
# description: Script to easily start, stop or restart TWCManager, or check the status.
# last update: Feb 2, 2020 by laur3ns

start() {
   echo -n "Starting TWCManager... "
   screen -S twc -Q select 2>&1 >/dev/null
   if [ $? -eq 0 ]; then
      echo "Already running, stop first!"
   else
      screen -dm -S twc -L -Logfile ~/scripts/twc/TWCManager.log ~/scripts/twc/TWCManager.py && echo "OK"
   fi
}

stop() {
   echo -n "Stopping TWCManager... "
   screen -S twc -X quit && echo "DONE"
   killall -q TWCManager.py
}

status() {
   # ps auxww | fgrep TWCManager | fgrep -v grep
   echo -n "TWC Manager running? "
   screen -S twc -Q select && echo "YES! To connect run 'screen -r twc' and exit with Ctrl-A, Ctrl-D"
}

case "$1" in 
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       status
       ;;
    status)
       status
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
